name: Input Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the building stage you want!"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Prod
          - Test
      artifact-tag:
        description: "Write Git Tag (version) to deploy ..."
        required: true
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App 
        run: echo " Successfuly Deploying the application with version ${{inputs.artifact-tag}} to ${{inputs.environment}}"
