name: If-conditions-demo
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      force_prod_deploy:
        description: "Choose staging environment"
        required: true
        type: choice
        options:
          - Develop
          - main
        default: Develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Running the intended main branch
        if: github.ref == 'refs/heads/main' 
        run: echo "Running this step"
      - name: Running another step
        run: echo "Hello from myside guys"
